# YOLO Dataset Quality Analysis Configuration File
# This file contains all default configuration parameters for the analysis

# ===========================
# DATASET CONFIGURATION
# ===========================
dataset:
  # Path to your YOLO dataset
  # Can be overridden with --dataset-path argument
  path: "/path/to/dataset"

  # Name for the FiftyOne dataset
  # This will be used for the dataset in FiftyOne and for thumbnail directories
  # Can be overridden with --dataset-name argument
  name: "default"

  # Dataset task type
  # Options: classify, detect, segment, pose, obb
  # Can be overridden with --dataset-task argument
  task: "detect"

  # Force reload dataset even if it exists
  # Set to true to reprocess everything from scratch
  # Can be overridden with --reload argument
  reload: false

# ===========================
# EMBEDDING CONFIGURATION
# ===========================
embeddings:
  # Skip embedding computation (useful for quick visualization)
  # Can be overridden with --skip-embeddings argument
  skip: false

  # CLIP model to use for embeddings
  # Available models are listed in src/enum.py under EmbeddingsModel
  model: "openai_clip"

  # Path to save the downloaded embeddings models
  dir: "./models/fiftyone"

  # Batch size for embedding computation
  batch_size: 16

# ===========================
# THUMBNAIL CONFIGURATION
# ===========================
thumbnails:
  # Directory to save thumbnails
  # Will be created inside the FiftyOne dataset directory
  dir: "thumbnails"

  # Width of the thumbnails (in pixels), height is scaled proportionally
  width: 800
